services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 123
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - keycloak-mysql